---
apiVersion: v1
kind: Service
metadata:
  name: express-cuts-frontend
  labels:
    app: ui
    role: frontend
    group: express-cuts
spec:
  type: NodePort 
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: ui
    role: frontend
    group: express-cuts