---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-cuts-frontend
  labels:
    app: ui
    role: frontend
    group: express-cuts
spec:
  selector:
    matchLabels:
      app: ui
      role: frontend
      group: express-cuts
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
        role: frontend
        group: express-cuts
    spec:
      restartPolicy: Always
      containers:
      - name: express-ui
        image: isaacrivriv/express-cuts-ui:phase3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: REST_API_URI
          valueFrom:
            secretKeyRef:
              name:  express-secret
              key: REST_API_URI
        volumeMounts:
        - mountPath: /etc/nginx/conf.d # mount nginx-conf volume to /etc/nginx
          readOnly: true
          name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
