---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: express-cuts-database
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: db
      group: express-cuts
  template:
    metadata:
      labels:
        app: postgres
        role: db
        group: express-cuts
    spec:
      containers:
      - name: postgres
        image: postgres:12.4
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresdb-data
          mountPath: /var/lib/pgsql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresdb-data
      labels:
        app: postgres
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200M