---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  labels:
    volume: postgres-volume
    group: express-cuts
    app: postgres
spec:
  capacity:
    storage: 200M
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/pgsql/data"