# Generated by Django 3.1.1 on 2020-09-12 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_service.user')),
                ('available', models.BooleanField()),
                ('profile_details', models.CharField(max_length=200)),
            ],
            bases=('express_service.user',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='express_service.user')),
                ('prefer_stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express_service.stylist')),
            ],
            bases=('express_service.user',),
        ),
    ]
