---
apiVersion: v1
kind: Secret
stringData:
  DATABASE_HOST: "express-cuts-database" # Could change if the stateful set or service is modified
  DATABASE_PORT: "5432" # Could change if the stateful set or service is modified
  DJANGO_SECRET_KEY: # Secret app key
  DJANGO_ALLOWED_HOSTS: # Allowed hosts
  DJANGO_CORS_ORIGIN_WHITELIST: # Whitelisted Cors
metadata:
  name: express-secret
  labels:
    app: rest-api
    role: backend
    group: express-cuts
type: Opaque